### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-js-vue-intro#2]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://absorbed-plastic.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/js-vue-intro/1) criteria:
- [x] There's an input box on the screen, for the user to talk to the chatbot
- [x] We're keeping track of `userInput` in our `data` Vue option, which starts out as an empty string
- [x] When the user types into the input box, our `userInput` data should automatically be updated
- [x] We're keeping track of the chatbot's `response` in our `data` Vue option, which starts out as an empty string
- [x] The `response` is displayed on the page in a `p` element below the input box
- [x] If the `response` is empty, the element with the `response` inside it is NOT rendered on the page
- [x] When a user presses enter inside the input box, we run a method that updates the response to contain a new string
- [x] If a user enters "hi" or "hello", the bot's response updates to "Greetings, human!"
- [x] If a user enters "how are you?", the response should be "I came into being through the excellent programming of my creator!"
- [x] The chatbot has specific responses to at least 3 other possible inputs (you make these up)
- [x] If the chatbot doesn't have a specific response to what the user entered, it randomly responds with one of at least 3 phrases to make it seem like it's listening - for example, "Very interesting! Tell me more." or "I guess that's one way to look at it."
- [x] The [`.toLowerCase()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase) method is used when checking what the user entered, so that it doesn't make a difference whether they type uppercase or lowercase letters

**Comment by chrisvfritz** [comment]
Wow, I don't like to throw this word around, but I think it's actually _perfect_. :+1: :tada: :balloon: :rocket: :dancer: :dart: :joy_cat: :shipit:
